board: 6x CNC Controller
name: Modded MPCNC

stepping:
  engine: I2S_STATIC
  idle_ms: 255
  pulse_us: 6
  dir_delay_us: 0
  disable_delay_us: 0

#uart channel 1 designated for Airdale IO expander board:
uart1:
  txd_pin: gpio.25
  rxd_pin: gpio.27
  baud: 1000000
  mode: 8N1
  passthrough_baud: 57600
  passthrough_mode: 8E1

uart_channel1:
  report_interval_ms: 50
  uart_num: 1

  #Airdale IO Expander Board
user_Inputs:
  digital0_pin: uart_channel1.0
  digital1_pin: uart_channel1.1
  digital2_pin: NO_PIN
  digital3_pin: NO_PIN
  digital4_pin: NO_PIN
  digital5_pin: NO_PIN
  digital6_pin: NO_PIN
  digital7_pin: NO_PIN

# Stepper Driver and Settings
# Nema 23 Stepper Motors: 6 x StepperOnline 23HS32-4004S
# Stepper chopper drivers: 6 x StepperOnline DM556T 4.0
# All motors are set to 8 microsteps @ RMS 2.3A

axes:
  shared_stepper_disable_pin: NO_PIN
  x:
    steps_per_mm: 50.000
    max_rate_mm_per_min: 9000.000
    acceleration_mm_per_sec2: 200.000
    max_travel_mm: 2440.00
    soft_limits: false
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: 3
      feed_mm_per_min: 300.000
      seek_mm_per_min: 1500.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.2:pu
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 5.000
      standard_stepper:
        step_pin: I2SO.2
        direction_pin: I2SO.1
        disable_pin: I2SO.0

    motor1:
      limit_neg_pin: gpio.26:pu
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 5.000
      standard_stepper:
        step_pin: I2SO.5
        direction_pin: I2SO.4
        disable_pin: I2SO.7

  y:
    steps_per_mm: 50.000
    max_rate_mm_per_min: 9000.000
    acceleration_mm_per_sec2: 200.000
    max_travel_mm: 2440.00
    soft_limits: false
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: 3
      feed_mm_per_min: 300.000
      seek_mm_per_min: 1500.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.32:pu
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 5.000
      standard_stepper:
        step_pin: I2SO.10
        direction_pin: I2SO.9
        disable_pin: I2SO.8

    motor1:
      limit_neg_pin: gpio.35
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 5.000
      standard_stepper:
        step_pin: I2SO.13
        direction_pin: I2SO.12
        disable_pin: I2SO.15

  z:
    steps_per_mm: 200.000
    max_rate_mm_per_min: 900.000
    acceleration_mm_per_sec2: 80.000
    max_travel_mm: 300.00
    soft_limits: false
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 200.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 800.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: gpio.34
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 5.000
      standard_stepper:
        step_pin: I2SO.18
        direction_pin: I2SO.17
        disable_pin: I2SO.16

  # Extra motor reservers for 4th Rotary  Axis

  # a:
  #   steps_per_mm: 50.000
  #   max_rate_mm_per_min: 9000.000
  #   acceleration_mm_per_sec2: 200.000
  #   max_travel_mm: 2440.00
  #   soft_limits: false
  #   homing:
  #     cycle: 2
  #     positive_direction: false
  #     mpos_mm: 0
  #     feed_mm_per_min: 300.000
  #     seek_mm_per_min: 1500.000
  #     settle_ms: 500
  #     seek_scaler: 1.100
  #     feed_scaler: 1.100

  # motor0:
  #   limit_neg_pin: gpio.39:low
  #   limit_pos_pin: NO_PIN
  #   limit_all_pin: NO_PIN
  #   hard_limits: false
  #   pulloff_mm: 1.000
  #   standard_stepper:
  #     step_pin: I2SO.21
  #     direction_pin: I2SO.20
  #     disable_pin: I2SO.23

i2so:
  bck_pin: gpio.22
  data_pin: gpio.21
  ws_pin: gpio.17

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  card_detect_pin: NO_PIN
  cs_pin: gpio.5

start:
  must_home: true

10V:
  forward_pin: gpio.15
  reverse_pin: gpio.14
  pwm_hz: 5000
  output_pin: gpio.13
  enable_pin: NO_PIN
  direction_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  spinup_ms: 0
  spindown_ms: 0
  tool_num: 0
  speed_map: 0=0.000% 1000=0.000% 24000=100.000%
  off_on_alarm: false

probe:
  pin: uart_channel1.0:low # Z-Probe pin for Airdale IO expander board
  # toolsetter_pin: N0_PIN

control:
  safety_door_pin: uart_channel1.1:low # Maps pin 8 of the Airedale(uart1) for Emergancy Stop or saftey door.
